### ISSUE TITLE
为什么你们的YuLan-Chat-2-13b模型这么大？

### ISSUE THREAD

**Issue by w179962443** [RUC-GSAI/YuLan-Chat#7]
https://huggingface.co/yulan-team/YuLan-Chat-2-13b/tree/main
是精度原因吗？我看你们这个13b模型本身就占50G，但是其他13b模型我看都是27G左右。当然，27G模型load到显卡也是50G显存占用。这个我感觉是精度是fp32，各位觉得对吗。

**Comment by w179962443** [comment]
但是config.json显示类型是bfloat16，我晕了。

**Comment by DaoD** [comment]
十分抱歉，我们一开始上传了一个FP32的模型，导致模型很大，后来上传了一个FP16的模型，链接是：https://huggingface.co/yulan-team/YuLan-Chat-2-13b-fp16
